# services:
#   web:
#     build: .
#     ports:
#       - '8080:8000'
#     environment:
#       - DATABASE_URL=postgres://user:password@db:5432/messaging_app
#       - SECRET_KEY=your_secret_key_here

#   db:
#     image: mysql:latest
#     ports:
#       - '3308:3306'
#     environment:
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#       MYSQL_DB: messaging_app
#     volumes:
#       - db_data:/var/lib/mysql/data

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

volumes:
  mysql_data:
