pipeline {
    agent {
        label 'master'
    }

    tools {
        python 'Python 3'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/uthmanduro/alx-backend-python.git'
            }
        }

        stage('Install Dependencies & Run Tests') {
            steps {
                withPythonEnv('venv') {
                    sh '''
                        cd messaging_app/messaging_app
                        pip3 install -r requirements.txt
                        pytest --junitxml=report.xml
                    '''
                }
            }
        }

        stage('Publish Test Report') {
            steps {
                junit 'messaging_app/messaging_app/report.xml'
            }
        }

        stage('Build Docker image') {
            steps {
                sh '''
                    docker build -t messaging_app:latest messaging_app/messaging_app
                    docker push messaging_app:latest
                '''
            }
        }
    }
}

