pipeline {
    agent {
        // Use ShiningPanda's Python virtualenv
        label 'master'
    }

    tools {
        // Python installed by ShiningPanda
        python 'Python 3'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git credentialsId: 'github', url: 'https://github.com/uthmanduro/alx-backend-python/messaging_app/messaging_app.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest --junitxml=report.xml'
            }
        }

        stage('Publish Test Report') {
            steps {
                junit 'report.xml'
            }
        }
    }
}
